// import { StyleSheet } from "react-native";

// export default StyleSheet.create({
//   container: { flex: 1, padding: 10 },
//   card: { marginBottom: 10 },
//   image: { height: 200, width: "100%", marginTop: 5 },
//   input: { marginBottom: 10 },
//   fab: {
//     position: "absolute",
//     bottom: 20,
//     right: 20,
//     backgroundColor: "#4CAF50",
//     width: 60,
//     height: 60,
//     borderRadius: 30,
//     justifyContent: "center",
//     alignItems: "center",
//   },
//   fabText: { fontSize: 24, color: "#fff" },
//   mapButton: {
//     position: "absolute",
//     bottom: 20,
//     left: 20,
//     backgroundColor: "#2196F3",
//     width: 60,
//     height: 60,
//     borderRadius: 30,
//     justifyContent: "center",
//     alignItems: "center",
//   },
// });

import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: "#a2a183",
  },
  card: {
    marginBottom: 16,
    borderRadius: 12,
    backgroundColor: "#686236",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    padding: 12,
  },
  image: {
    height: 220,
    width: "100%",
    borderRadius: 10,
    marginTop: 8,
  },
  input: {
    marginBottom: 10,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#EFEFEF",
    fontSize: 16,
  },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    backgroundColor: "#132d3a",
    width: 64,
    height: 64,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    marginBottom: 24,
  },
  fabText: {
    fontSize: 28,
    color: "#fff",
    fontWeight: "600",
  },
  mapButton: {
    position: "absolute",
    bottom: 24,
    left: 24,
    backgroundColor: "#686236",
    width: 94,
    height: 64,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    marginBottom: 24,
  },
});
